# Generated by Django 2.1.3 on 2018-11-16 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('headline', models.CharField(blank=True, max_length=150)),
                ('interest_areas', models.CharField(blank=True, max_length=100)),
                ('regions', models.CharField(blank=True, max_length=100)),
                ('foundation', models.CharField(blank=True, max_length=100)),
                ('employees', models.CharField(blank=True, max_length=100)),
                ('units', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('published', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('cnpj', models.CharField(blank=True, max_length=100)),
                ('owner_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
