# Generated by Django 2.1.3 on 2018-11-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectImages',
            new_name='ProjectImage',
        ),
    ]
